### ISSUE TITLE
New block syntax: datatable with YAML 

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-standoc#106]
Syntax:

```adoc
=== Data model

// This is implemented in the metanorma-standoc/datamodel branch
[datamodel]
....
include::../instances/DataInstance.yml[]
....

// This is the YAML data table
=== Data instances

[datatable,yaml]
....
include::../instances/*.yml[]
....

```

=> a table that shows the attributes and values of each data instance.

e.g. ISO 19108

<img width="609" alt="Screen Shot 2019-09-04 at 2 49 46 PM" src="https://user-images.githubusercontent.com/11865/64231845-3f0afb00-cf23-11e9-91b8-1d575cccedf0.png">

<img width="602" alt="Screen Shot 2019-09-04 at 2 49 59 PM" src="https://user-images.githubusercontent.com/11865/64231868-46ca9f80-cf23-11e9-9acc-d853380931a4.png">

**Comment by ronaldtse** [comment]
Given a data instance YAML like this:

(something like this...)
```yaml
TM_ReferenceSystem:
  name: Julian calendar
  domainOfValidity: Western Europe
  calendar <TM_Calendar>:
    dateTrans:
      description: |
        Algorithm for transformation of Julian calendar date
        (Y/M/D) to Julian date (J).
      value: |
        Y' = ...
    julTrans:
      description: |
        Algorithm for transformation of Julian date (J) into
        Julian calendar date (Y/M/D).
      value: |
        J' = ...
  basis:
    - <TM_CalendarEra>
      name: Christian era
      referenceEvent: Birth of Jesus Christ
      referenceDate: 01, 01, 01
      julianReference: 1721424
      epochOfUse:
        begin: 2087769
        end: 2299160
```
