### ISSUE TITLE
yaml2text: not working with a typical use case

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-standoc#260]
authority-codes.yaml
```yaml
data:
  acadsin-zho-hani-latn-2002:
    code: acadsin-zho-hani-latn-2002
    name:
      en: Academica Sinica -- Chinese Tongyong Pinyin (2002)
    authority: acadsin
    lang:
      system: iso-639-2
      code: zho
    source_script: Hani
    target_script: Latn
    system:
      id: '2002'
      specification: Academica Sinica -- Chinese Tongyong Pinyin (2002)
    notes: 'NOTE: OGC 11-122r1 code `zho_Hani2Latn_AcadSin_2002`'
```

```adoc
[yaml2text,sources/data/authority-codes.yaml,authorities]
----
[cols="a,a,a",options="header"]
|===
| Script conversion system authority code | Name in English | Notes

{authorities.data.*,key,EOI}
| {key} | {authorities.data[key]['code']} | {authorities.data[key]['notes']}
{EOI}

|===
----
```

Error:
```
NameError: asciidoctor: FAILED: sources/cc-24229.adoc: Failed to load AsciiDoc document - undefined local variable or method `current_block_attrs' for #<Asciidoctor::Standoc::Yaml2TextPreprocessor:0x00007fa1a3357590>
```
