### ISSUE TITLE
Align font requirements with HTML (plain and Word) and PDF expectations

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-standoc#383]
Each Metanorma flavor + output format has a specific set of fonts to be used.

In HTML/browsers, the fonts specified need to use a browser understandable name for `font-face` and `font-family`.

In CSS 4, these two messages indicate:
https://github.com/w3c/csswg-drafts/issues/3177#issuecomment-431773808
https://github.com/w3c/csswg-drafts/issues/3177#issuecomment-432131599

That for HTML CSS fonts we should only use "full font name" (i.e. without style) and "postscript name"

And in Chrome:
https://stackoverflow.com/questions/24849224/css-font-family-which-name-does-css-font-use

So say for "Overpass" (https://github.com/fontist/formulas/blob/master/Formulas/overpass.yml)

```yaml
- name: Overpass
  styles:
  - family_name: Overpass
    type: Bold Italic
    full_name: Overpass Bold Italic
    post_script_name: Overpass-BoldItalic
```

The HTML CSS font name is "Overpass" (family name) or the postscript name "Overpass-BoldItalic"

**Comment by ronaldtse** [comment]
This is relevant to the ongoing PRs:

 - https://github.com/metanorma/metanorma-generic/pull/54
 - https://github.com/metanorma/metanorma-un/pull/90
 - https://github.com/metanorma/metanorma-ogc/pull/215
 - https://github.com/metanorma/metanorma-mpfa/pull/67
 - https://github.com/metanorma/metanorma-m3aawg/pull/68
 - https://github.com/metanorma/metanorma-itu/pull/256
 - https://github.com/metanorma/metanorma-iso/pull/447
 - https://github.com/metanorma/metanorma-iho/pull/38
 - https://github.com/metanorma/metanorma-iec/pull/89
 - https://github.com/metanorma/metanorma-gb/pull/147
 - https://github.com/metanorma/metanorma-csa/pull/59
 - https://github.com/metanorma/metanorma-cc/pull/125

Thanks @CAMOBAP !

**Comment by ronaldtse** [comment]
@Intelligent2013 could you also help verify the font names needed for mn2pdf so @CAMOBAP can help align them here? Thanks!

**Comment by CAMOBAP** [comment]
@ronaldtse to be on the same page where should we list those postscript font names? in fonts_manifest.yaml?

**Comment by ronaldtse** [comment]
I think Fontist only accepts the family name right now? (Ping @alexeymorozov)

I wonder in the future we could use fontist as a dependency where you can get the appropriate names of fonts in order to pass the names to the output formats.

**Comment by Intelligent2013** [comment]
The font names needed for mn2pdf:

**bipm**:
- Arial
- Times New Roman
- Work Sans
- STIX Two Math
- Source Han Sans

**csa**:
- Azo Sans
- Azo Sans Lt
- STIX Two Math
- Source Code Pro

**cc**:
- Source Sans Pro
- STIX Two Math
- Source Han Sans
- Source Code Pro

**gb**:
- SimSun
- SimHei
- Cambria
- Cambria Math
- Courier

**iec**:
- Arial
- Times New Roman
- STIX Two Math
- Source Han Sans
- Courier

**iho**:
- Helvetica Neue
- Cambria Math
- SF Mono
- Courier
- STIX Two Math

**iso**:
- Cambria
- Cambria Math
- Times New Roman
- Source Han Sans
- Courier

**itu**:
- Times New Roman
- STIX Two Math
- Arial
- Courier

**m3d**:
- Garamond
- Arial
- Cambria Math
- Courier

**mpfd**:
- Arial
- STIX Two Math

**nist**:
- Times New Roman
- STIX Two Math
- Calibri
- Arial
- Courier

**ogc**:
- Lato
- Arial
- STIX Two Math
- Source Han Sans
- Fira Code
- Courier

**rsd**:
- Source Sans Pro
- STIX Two Math
- Source Serif Pro
- Source Code Pro

**un**:
- Times New Roman
- STIX Two Math
- Source Han Sans
- Arial
- Arial Black
- Courier


Note: Source Han Sans font in most cases needs for char replacement when old windows font version is using. For example, in old windows Times New Roman font there aren't some white-spaces glyphs, and if we don't specify 'Source Han Sans' font, then we see '#' char in PDF.

**Comment by CAMOBAP** [comment]
@ronaldtse those fonts above should be added to fonts_manifest.yaml too, right?

**Comment by ronaldtse** [comment]
@CAMOBAP yes, that's correct.

**Comment by ronaldtse** [comment]
We have some problems with the fonts here:

* For `iho`, we can't use "SF Mono" because it has a font license that does not allow general usage.
* We can't find a freely licensed Helvetica Neue.

@Intelligent2013 anything we can change here?

**Comment by ronaldtse** [comment]
@Intelligent2013 actually I don't see where IHO uses SF Mono or Helvetica Neue. Let's change to Fira Code and Neue Haas Grotesk instead.

In addition, Azo Sans is available on macOS by default, but not freely licensed. We will have to find an alternative.

**Comment by Intelligent2013** [comment]
> @Intelligent2013 actually I don't see where IHO uses SF Mono or Helvetica Neue. Let's change to Fira Code and Neue Haas Grotesk instead.

@ronaldtse ok.
FYI, IHO xslt was developed for source doc templates in gh-pages branch (for example, https://raw.githubusercontent.com/metanorma/mn-samples-iho/gh-pages/documents/b12.doc). The main font in docs is "Helvetica Neue":

```css
p.MsoNormal, li.MsoNormal, div.MsoNormal {
  mso-style-unhide: no;
  mso-style-qformat: yes;
  mso-style-parent: "";
  margin: 0cm;
  margin-bottom: 12.0pt;
  mso-pagination: widow-orphan;
  font-size: 12.0pt;
  font-family: "Helvetica Neue",Arial,sans-serif;
  mso-fareast-font-family: "Times New Roman";
  mso-ansi-language: EN-US;
  mso-fareast-language: EN-US; }
```

For source code:
```css
p.Sourcecode, li.Sourcecode, div.Sourcecode, pre.Sourcecode, pre {
  mso-style-unhide: no;
  mso-style-qformat: yes;
  mso-style-parent: "";
  margin-top: 6.0pt;
  margin-right: 0cm;
  margin-bottom: 6.0pt;
  margin-left: 0cm;
  text-align: left;
  mso-pagination: widow-orphan;
  tab-stops: 45.8pt 91.6pt 137.4pt 183.2pt 229.0pt 274.8pt 320.6pt 366.4pt 412.2pt 458.0pt 503.8pt 549.6pt 595.4pt 641.2pt 687.0pt 732.8pt;
  font-size: 10.0pt;
  font-family: SFMono-Regular,Menlo,Monaco,Consolas,"Liberation Mono","Courier New",monospace;
  mso-fareast-font-family: Calibri;
  mso-bidi-font-family: "Courier New";
  mso-ansi-language: EN-GB; }
```

In case if font didn't install on system, then MS Word uses next first available font. In this case - Arial:
![изображение](https://user-images.githubusercontent.com/5559926/100612985-dfb5b980-3324-11eb-8877-19e031bf8670.png)
