### ISSUE TITLE
Unexpected rendering upon for loop in yaml2text block

### ISSUE THREAD

**Issue by manuel489** [metanorma/metanorma-standoc#409]
*In relation to https://github.com/ituob/service-publications-docs/issues/1*

We need to extract some data from existing YAML files. But I'm getting unexpected rendering upon `for` loop in `yaml2text` block.

In the example below, I'm trying to extract the country names (French, English and Spanish) from the indicated YAML file into an adoc table by using `for` loop.

**T-SP-SR.1-2012.yaml file**:

````
metadata:
...

data:
  Andorre:
    geographic_area:
      fr: Andorre
      en: Andorra
      es: Andorra
    restrictions:
      telex_not_provided: true
  Antigua-et-Barbuda:
    geographic_area:
      fr: Antigua-et-Barbuda
      en: Antigua and Barbuda
      es: Antigua y Barbuda
    restrictions:
      telegram_not_provided: true
      no_collect_calls:
        mobile: true
        payphone: true
        audiotex: true
  Argentine:
    geographic_area:
      fr: Argentine
      en: Argentina
      es: Argentina

...
````

`yaml2text` block:

````
[yaml2text,T-SP-SR.1-2012.yaml,file]
----
[%unnumbered,cols="1",options="header"]
|===
^.^|Country/geographical area

{% for country in file.data %}
a|  *{{ country.geographic_area.fr }}* +
    *{{ country.geographic_area.en }}* +
    *{{ country.geographic_area.es }}*
{% endfor %}
|===
----
````

It renders as:

![Capture](https://user-images.githubusercontent.com/33627611/104130101-462af000-5345-11eb-8f02-7192091c3682.PNG)

I expected something like this (only the country names):

![Capture2](https://user-images.githubusercontent.com/33627611/104130254-09abc400-5346-11eb-96bf-226748d668de.PNG)

Maybe I'm using the wrong markup?
