### ISSUE TITLE
Support for YAML repeated nodes in Liquid

### ISSUE THREAD

**Issue by manuel489** [metanorma/metanorma-standoc#469]
*In relation to https://github.com/ituob/service-publications-docs/issues/1*

I'm getting `Liquid error: internal` message on repeated nodes.

YAML example:
````
---
groups:
  amateur: &general
    regex: O[F-J][:digit:][0-9A-Z]{3}[:upper:]{1}

  experimental: *general
````
being `&general` a node object, and `*general` the reference to that object.
