### ISSUE TITLE
Collection: support cross-document references with independent documents

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-standoc#746]
From @anermina in metanorma/mn-samples-bsi#198 :

> PAS 2030:
> * Some cross-references were missing because the original document referred to the non-existing sections/tables.
>   For example "see 5.6" refers to the section that exists in PAS 2035, but not PAS 2030.
>   Same applies to referencing 4.2.4 and 4.2.5. Anchors are removed and these are now just a plain text which should be changed.
> 
> PAS 2035:
> * Similar as above, section 10.9.1 doesn't exist.

This is a great discovery that we need to handle. The question is when we have an independent cross-document citations from Document A to Document B, and when both documents are now put into a collection, how do we link between them?

We have to assume that Document A and Document B are independent documents and their encoding should not be changed.

It is up to the collection configuration to indicate that these two documents link through a bibliographic item, and that that links pointing to each other should be collection-internal links.

This means we have to either explicitly state the connection between an item inside a collection to another item's bibliography, or implicitly match via publication identifiers.

This also means that the semantic XML content from both Document A and Document B are unchanged. It is only when they are composed in a collection that this cross-document reference redirection occurs.

## Method 1: explicitly state connections

```yaml
collection:
  components:
    - document-root: pas-2030.adoc
      identifier: pas2030
      bibliographic-item-mapping:
        - "PAS 2035:2019": pas2035
    - document-root: pas-2035.adoc
      identifier: pas2035
      bibliographic-item-mapping:
        - "PAS 2030:2019": pas2030
```

## Method 2: implicit publication identifier match

In pas2030.adoc
```
= Title
:doctype: PAS
:docnumber: 2030
:copyright-year: 2019

...
== Bibliography
* [[[pas2035,PAS 2035:2019]]]
```

In pas2035.adoc
```
:doctype: PAS
:docnumber: 2035
:copyright-year: 2019

...
== Bibliography
* [[[pas2030,PAS 2030:2019]]]
```

Then when inside a collection, the bibliographic items automatically match because the identifiers can be resolved in a collection.

_Originally posted by @ronaldtse in https://github.com/metanorma/mn-samples-bsi/issues/198#issuecomment-1435514368_

**Comment by opoudjis** [comment]
Method 2 was always the intent, and the proposal of Method 1 is ridiculous:

````
collection:
  components:
    - document-root: pas-2030.adoc
      identifier: pas2030
      bibliographic-item-mapping:
        - "PAS 2035:2019": pas2035
    - document-root: pas-2035.adoc
      identifier: pas2035
      bibliographic-item-mapping:
        - "PAS 2030:2019": pas2030
````

Congratulations, you've just reinvented the manifest. WHICH IS ALREADY THERE.

````
manifest:
  level: collection
  title: BSI PAS 2035 / PAS 2030 collection
  docref:
    - fileref: _site/documents/pas-2035/document.xml
      identifier: PAS 2035:2020
    - fileref: _site/documents/pas-2030/document.xml
      identifier: PAS 2030:2019
````
