### ISSUE TITLE
Empty result for HTML entities processing in yaml2text

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/metanorma-standoc#826]
Source issue: https://github.com/metanorma/pdfa-iso-32000-2/issues/4#issuecomment-1804659727

If the yaml file contains HTML entities like `&Alpha;`, then the Presentation XML doesn't contain any character.

In the sample document [document.zip](https://github.com/metanorma/metanorma-standoc/files/13322438/document.zip):
- 1st row encoded directly without `yaml2text` - renders ok
- 2nd row encoded with using of `yaml2text`, the entities `&Alpha;` and `&harr;` are using - empty result
- 3rd row  encoded with using of `yaml2text`, the entities `&#x0391;` and `&#x2194;` are using - renders ok

```adoc
| &Alpha; | Alpha | 101 | &harr; | arrowboth | 253

{% for row in table.rows %}
{% for character in row %}
| {{ character.entity }} | {{ character.name }} | {{ character.code -}}
{% endfor %}
{% endfor %}
```

`table.yaml`:
```yaml
---
id: D.5
title: Symbol set and encoding
rows:
  - - name: Alpha
      entity: "&Alpha;"
      code: 101
    - name: arrowboth
      entity: "&harr;"
      code: 253

  - - name: Alpha
      entity: "&#x0391;"
      code: 101
    - name: arrowboth
      entity: "&#x2194;"
      code: 253
```

The output Presentation XML:
```xml
<tbody>
	<tr>
		<td valign="top" align="left">Α</td>
		<td valign="top" align="left">Alpha</td>
		<td valign="top" align="left">101</td>
		<td valign="top" align="left">↔</td>
		<td valign="top" align="left">arrowboth</td>
		<td valign="top" align="left">253</td>
	</tr>
	<tr>
		<td valign="top" align="left"/>
		<td valign="top" align="left">Alpha</td>
		<td valign="top" align="left">101</td>
		<td valign="top" align="left"/>
		<td valign="top" align="left">arrowboth</td>
		<td valign="top" align="left">253</td>
	</tr>
	<tr>
		<td valign="top" align="left">Α</td>
		<td valign="top" align="left">Alpha</td>
		<td valign="top" align="left">101</td>
		<td valign="top" align="left">↔</td>
		<td valign="top" align="left">arrowboth</td>
		<td valign="top" align="left">253</td>
	</tr>
</tbody>
```

Resulted PDF:
![image](https://github.com/metanorma/metanorma-standoc/assets/5559926/e007725c-5f25-4e53-9761-642732cc16f6)
