### ISSUE TITLE
Need functionality to format numbers

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-standoc#882]
From metanorma/iso-2533#22

In ISO 2533 we have raw numbers coming from YAML like this:

`sources/iso-2533-2024/yaml/table7.yaml`:
```yaml
  - geometrical-altitude-m: -5000
    geometrical-altitude-ft: -16404
    geopotential-altitude-m: -5004
    geopotential-altitude-ft: -16417
    pressure-scale-height: 9371.8
    specific-weight: 18.968
    air-number-density: 4.0154e+25
    mean-speed: 484.15
    frequency: 11507000000.0
    mean-free-path: 4.2075e-08
```

And these numbers are rendered in the document, as plain text:

<img width="544" alt="Screenshot 2024-04-01 at 12 36 13" src="https://github.com/metanorma/iso-2533/assets/11865/9abd3660-2769-43c8-918c-14b223ad8cbe">

There are several problems with regards to number formatting:
1. I can't use `stem:[...]` because it would take forever in processing (Plurimath performance problem, MathML bloating problem in XML). For example, if all the numbers are in MathML, Safari can't even load the file due to MathJax having to render so many numbers.
2. These values are not formatted according to ISO 80000. This will be an editorial issue.
3. I can't choose the number format, e.g. if I wanted to shift the `e`, or if I wanted to shrink `11507000000.0` into something more manageable.

If we address these issues one by one:
1. We fix Plurimath. When it's just a number, we do not use MathML...? But if it has a unit, we need to UnitsML+MathML.
2. We implement an ISO 80000 profile for Plurimath-rendered plain numbers.
3. We implement some number formatting command...?

Thoughts needed.
