### ISSUE TITLE
standoc not auto-released on version pushed

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-standoc#892]
In the rake workflows, the release workflow for standoc was changed so that it was triggered by pushing a new version of the gem, not by the successful completion of the GHA testing of it. This behaviour has just reverted in the latest release. I hadn't noticed it, but it seems to have reverted for isodoc as well.

**Comment by opoudjis** [comment]
@CAMOBAP Still not resolved.

**Comment by CAMOBAP** [comment]
From what I see in the logs it was 

https://github.com/metanorma/metanorma-standoc/actions/runs/10034368952 was triggered by tests executed on main branch after tag on main was added

@opoudjis any proofs/logs/observations that release was happens without testing?

**Comment by opoudjis** [comment]
The requirement was that the release _should_ happen without testing, because of how time consuming the tests are. This was implemented in https://github.com/metanorma/metanorma-standoc/issues/881 , https://github.com/metanorma/metanorma-standoc/commit/3475d94c30bba5ed6a755cd4ca362ab91dc13211


````
  push:
    tags: [ v* ]
````

appears to be the required trigger, and this was reverted in https://github.com/metanorma/metanorma-standoc/commit/d506acd57cf4d74d8c3c7a81ff4e5ce3e3ab86b6

**Comment by CAMOBAP** [comment]
Sorry, this was overwritten from cimas configuration... applied again

@ronaldtse I just inform you that I don't see any sense of swimming against the flow anymore I will turn off pre-release unit testing on ci because @opoudjis **STRONGLY** against it.

If we have turned it off for some repos like `isodoc` and `metanorma-standoc` what is the point of keeping it for other repos?

The changes will be applied on the mass update https://github.com/metanorma/ci/pull/175

**Comment by ronaldtse** [comment]
@CAMOBAP I understand. I wonder if there is a way we can streamline the test/release flow...

**Comment by CAMOBAP** [comment]
@ronaldtse I have some idea to streamline releases https://github.com/metanorma/metanorma-release/issues/21 unfortunately i never reached this task...

**Comment by opoudjis** [comment]
> @ronaldtse I just inform you that I don't see any sense of swimming against the flow anymore I will turn off pre-release unit testing on ci because @opoudjis **STRONGLY** against it.
> 
> If we have turned it off for some repos like `isodoc` and `metanorma-standoc` what is the point of keeping it for other repos?

I think they do remain useful, and they are routinely catching things, especially in Windows. It's just that because everything depends on isodoc and standoc, making them subject to pre-release testing in the current setup is simply slowing everything else down too much; I regard them as necessary exceptions.

**Comment by opoudjis** [comment]
Has come back, this time for isodoc:

https://github.com/metanorma/isodoc/blob/main/.github/workflows/release.yml

````
name: release

on:
  workflow_dispatch:
    inputs:
      next_version:
        description: |
          Next release version. Possible values: x.y.z, major, minor, patch (or pre|rc|etc).
          Also, you can pass 'skip' to skip 'git tag' and do 'gem push' for the current version
        required: true
        default: 'skip'
  repository_dispatch:
    types: [ do-release ]
````
